### ISSUE TITLE
Batch FTP on Linux crashes on upload

### ISSUE THREAD

**Issue by mbuckaway** [esitarski/CrossMgr#53]
**Describe the bug**
After the race has been run, go to Batch FTP menu item, select batch upload for Index and Html, and click process all. The first file (index?) uploads, and the second file causes a segfault. CrossMgr exits and must be restarted.

**To Reproduce**
1. Batch FTP menu item, select batch upload for Index and Html
2. Click on 'Process All"
3. Crash

**Expected behavior**
All files would be uploaded and dialog disappears.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.06LTS
 - Version: Current Development release: 3.0.46-beta

**Additional context**
Upload was at the FCV where the upload speed is 500kbps...slow. Not sure what happens on Mac or Windows. After the problem happened one race, I gave up. Could be race related....as the number of laps was 450.

**Comment by mbuckaway** [comment]
Some work was done on this issue. A dialog box warning the user that using these FTP tools during a race is a bad idea.

**Comment by esitarski** [comment]
There was a Mac bug that was fixed a few months ago.
It was related to generating the html, but it would also cause a crash during FTP (which of course, requires the HTML to be generated first).
The number of laps is not a factor.

I cannot make CrossMgr crash with Batch FTP upload on a Mac.
Can you confirm this problem is solved?

**Comment by mbuckaway** [comment]
Nope. Don't have the system or CrossMgr setup anymore.
